baseURL = "https://rifanlab.my.id/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Achmad Rif'an"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  links = [
    { href = "https://rifan.pages.dev/", text = "Rifan" },
    { email = "mailto:withrifan@gmail.com" },
    { linkedin =  "https://linkedin.com/in/achmadrifan" },
    { github = "https://github.com/withrifan" },
    { gitlab = "https://gitlab.com/withrifan" },
    { facebook = "https://facebook.com/withrifan" },
    { instagram = "https://instagram.com/withrifan" }
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
