baseURL = "https://rifanlab.my.id/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Achmad Rif'an"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  links = [
    { email = { href = "mailto:withrifan@gmail.com", text = "Contact Me" } },
    { link = { href = "https://rifan.pages.dev/", text = "Main Website" } },
    { linkedin = { href = "https://linkedin.com/in/achmadrifan", text = "My LinkedIn" } },
    { github = { href = "https://github.com/withrifan", text = "GitHub Project" } },
    { gitlab = { href = "https://gitlab.com/withrifan", text = "GitLab Project" } },
    { facebook = { href = "https://facebook.com/withrifan", text = "My Facebook" } },
    { instagram = "https://instagram.com/withrifan" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
