baseURL = "https://rifanlab.my.id/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Rif'an Lab"
copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Achmad Rif'an"
  headline = "started with Bismillah, finished with Hamdalah"
  image = "resources\_gen\images\profile.png"

  links = [
    { email = { href = "mailto:withrifan@gmail.com", text = "Contact Me" } },
    { link = { href = "https://rifan.pages.dev/", text = "My Main Website" } },
    { linkedin = { href = "https://linkedin.com/in/achmadrifan", text = "My LinkedIn" } },
    { github = { href = "https://github.com/in/withrifan", text = "GitHub Project" } },
    { gitlab = { href = "https://gitlab.com/in/withrifan", text = "Gitlab Project" } },
    { facebook = { href = "https://linkedin.com/in/withrifan", text = "Facebook" } },
    { instagram = { href = "https://linkedin.com/in/withrifan", text = "Instagram" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
